export const INDUSTRIES = [
  {
    slug: "it-companies",
    label: "IT Companies",
    icon: "💻",
    metaTitle: "Corporate Gifts for IT Companies in India",
    description: "Tech-forward gifting for software companies, product firms and IT services — from premium tech accessories to custom branded merchandise.",
    popularProducts: ["Wireless Earbuds", "Laptop Bags", "Custom Mousepads", "Smart Bottles"],
  },
  {
    slug: "pharma",
    label: "Pharma",
    icon: "💊",
    metaTitle: "Corporate Gifts for Pharma Industry",
    description: "Professional gifting solutions for pharmaceutical companies — doctor gifts, MR kits, and conference merchandise.",
    popularProducts: ["Executive Pens", "Conference Kits", "Branded Bags", "Premium Diaries"],
  },
  {
    slug: "manufacturing",
    label: "Manufacturing",
    icon: "🏭",
    metaTitle: "Corporate Gifts for Manufacturing Sector",
    description: "Durable, practical gifting for manufacturing companies — safety kits, branded workwear, and functional accessories.",
    popularProducts: ["Branded Caps", "Safety Kits", "Drinkware", "Tool Kits"],
  },
  {
    slug: "education",
    label: "Education",
    icon: "🎓",
    metaTitle: "Corporate Gifts for Educational Institutions",
    description: "Thoughtful gifting for schools, colleges and EdTech companies — student kits, teacher appreciation gifts, and graduation hampers.",
    popularProducts: ["Stationery Sets", "Backpacks", "Notebooks", "Gift Hampers"],
  },
  {
    slug: "hospitals",
    label: "Hospitals",
    icon: "🏥",
    metaTitle: "Corporate Gifts for Healthcare Industry",
    description: "Premium gifting for hospitals, clinics and healthcare organisations — doctor appreciation kits, staff gifts, and patient care hampers.",
    popularProducts: ["Wellness Hampers", "Premium Diaries", "Branded Bags", "Eco-Friendly Gifts"],
  },
  {
    slug: "hotels",
    label: "Hotels",
    icon: "🏨",
    metaTitle: "Corporate Gifts for Hospitality Sector",
    description: "Luxury gifting for hotels and hospitality companies — guest welcome kits, staff appreciation gifts, and event merchandise.",
    popularProducts: ["Luxury Hampers", "Premium Drinkware", "Scented Candles", "Custom Boxes"],
  },
  {
    slug: "banking",
    label: "Banking & BFSI",
    icon: "🏦",
    metaTitle: "Corporate Gifts for Banking Sector",
    description: "Professional, premium gifting for banks and financial institutions — client gifts, employee kits, and premium branded merchandise.",
    popularProducts: ["Executive Gift Sets", "Premium Pens", "Leather Accessories", "Gift Hampers"],
  },
  {
    slug: "fmcg",
    label: "FMCG",
    icon: "🛒",
    metaTitle: "Corporate Gifts for FMCG Companies",
    description: "High-volume, impactful gifting for FMCG brands — distributor gifts, dealer meet kits, and promotional merchandise.",
    popularProducts: ["Branded T-Shirts", "Custom Caps", "Gift Hampers", "Promotional Merchandise"],
  },
  {
    slug: "startups",
    label: "Startups",
    icon: "🚀",
    metaTitle: "Corporate Gifts for Startups",
    description: "Cool, creative gifting for startups — employee onboarding kits, investor gifts, and branded merchandise that reflects your culture.",
    popularProducts: ["Welcome Kits", "Branded Hoodies", "Tech Accessories", "Eco-Friendly Gifts"],
  },
] as const;

export type IndustrySlug = typeof INDUSTRIES[number]["slug"];
